name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels:

    * type:feature

body:

    * type: textarea
          id: problem
          attributes:
          label: Problem
          description: What problem are you trying to solve?

    * type: textarea
          id: solution
          attributes:
          label: Proposed Solution

    * type: textarea
          id: alternatives
          attributes:
          label: Alternatives Considered

    * type: textarea
          id: additional
          attributes:
          label: Additional Context
